### ISSUE TITLE
Request for transfer to textlint-ja organization

### ISSUE THREAD

**Issue by azu** [textlint-ja/textlint-rule-no-doubled-conjunction#3]
@takahashim こんにちは。

パッケージの管理についてのご相談です。
いろんな人でルールのメンテナンスを行えるように、パッケージを https://github.com/textlint-ja で管理できるようにしたいです。

具体的には次のあたりのアップデートをしていきたいです。

- textlint-scriptsの利用
- kuromoji@2 へアップデート

GitHubとnpmどちらもtextlint-jaのorganizationがあるため、そちらにリポジトリとパッケージの権限を移すことで、
複数人でメンテナンスできるようになります。

以下にtextlint-jaのポリシーを書いてあります。

- [textlint-ja/textlint-ja: textlintの日本語コミュニティ](https://github.com/textlint-ja/textlint-ja)

もしパッケージを https://github.com/textlint-ja に移すのが大丈夫なら、GitHubとnpmでそれぞれ招待をお送りします。

**Comment by takahashim** [comment]
@azu はい、textlint-ja organizationにtransferするのは問題ないです。
どういう手順で作業するのがよいですか？

**Comment by azu** [comment]
@takahashim ありがとうございます。

GitHubとnpm それぞれ textlint-ja へのinviteをお送りしたので、メールが来ていると思います。
Organizationに参加できたら

- GitHub: https://github.com/takahashim/textlint-rule-no-doubled-conjunction/settings から"Transfer"で `textlint-ja` にリポジトリを移譲
- npm: https://www.npmjs.com/settings/textlint-ja/teams/team/developers/access から"Add Packages to developers" に `textlint-rule-no-doubled-conjunction` を追加

でパッケージの権限がそれぞれ移行できると思います。

https://github.com/textlint-ja/textlint-ja#for-new-member

**Comment by azu** [comment]
後 https://github.com/takahashim/textlint-rule-no-doubled-conjunctive-particle-ga の方もお願いしようと思っていたのですが、同じようにIssueを作成したほうが良さそうですかね?

**Comment by takahashim** [comment]
`takahashim/textlint-rule-no-doubled-conjunctive-particle-ga` も合わせてtransferしてみました。
これで良さそうですか？

**Comment by azu** [comment]
ありがとうございます！ おそらく大丈夫だと思います。
リポジトリ情報を更新するPR出してみます。

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/88473185-023e5d00-cf56-11ea-8a11-acc787145860.png)

npm の方もCollaborators追加されているので問題なさそうです。

**Comment by azu** [comment]
リポジトリの情報を更新しました #4 

>     * textlint-scriptsの利用
>     * kuromojin@2 へアップデート

この辺も合わせてやっていきますね
